// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zweehdlhfqowvrzwzsvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3ZWVoZGxoZnFvd3Zyend6c3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNzYwODMsImV4cCI6MjA3NTg1MjA4M30.O2rXsPcmknE-1QD3BkHmgOy19XW6pDO8gCPxvLnJ-KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});